// Generated by CoffeeScript 1.7.1
(function() {
  var $container;

  $container = $('.image-grid');

  $container.imagesLoaded(function() {
    return $container.masonry({
      isFitWidth: true,
      itemSelector: 'img'
    });
  });

}).call(this);
